### ISSUE TITLE
3. Better modularization

### ISSUE THREAD

**Issue by michal-murawski-90poe** [jtarmitage/graphql-api#3]
Once we got the search, we could also improve the application's structure.

Imagine, it is not the simplest boilerplate but a new module of an already existing application. Try to follow Domain Driven Design (example: pages, components, services, etc.), you could even incorporate a few generic functions and types to show how would you approach this kind of structure.

**Comment by jtarmitage** [comment]
I have created a new branch which takes most of the code out of App.tsx and moves it to separate components. I could potentially add React Router to add separate pages.
