### ISSUE TITLE
4. Tests for business logic

### ISSUE THREAD

**Issue by michal-murawski-90poe** [jtarmitage/graphql-api#4]
Right now, we have a few simple tests for UI components. 

It would be great to extend them and test the application's core logic: fetching, async flow, searching, asserting the data in the table, etc.

**Note: please do not make direct calls to the GH API from your tests**

**Comment by jtarmitage** [comment]
I've added tests for the fetching and asserting data, though I'll keep this open too as I'll want to update these tests if I add pagination.
