### ISSUE TITLE
5. Add pagination (nice to have)

### ISSUE THREAD

**Issue by michal-murawski-90poe** [jtarmitage/graphql-api#5]
The cherry on top! Once we have everything prepared, we could add basic pagination to our table (the assumption is, we are querying the API, not pagination on the client side). This task is nice to have 💯 

**Note: GitHub's graphql API is sometimes returning unexpected results. If you face some problems, please describe them and explain what was wrong and what could be the solution.**

**Comment by jtarmitage** [comment]
Simple pagination has now been added. I was hoping to be able to add numbered pagination, e.g. Previous and Next buttons, with 1-10 in the middle, changing to 2-11, 3-12 as the pages change. However the GraphQL API doesn't appear to offer numbered offsets for search, which means that we have to use cursor based pagination and can't directly address a specific page.
